sudo: false
language: node_js
node_js:
  - "5"
  - "6"
services:
  - postgresql
before_script:
  - psql -c 'create database test_db;' -U postgres
script:
  - "npm run lint"
  - "npm test"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
