language: node_js
node_js:
  - "4.1"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
services:
  - redis-server
env:
  - TRAVIS=travis CXX=g++-4.8 fakeusername=$2a$04$M.JTXZG1fG0kHlyhzaeDR.ufF9fbJ5fWsqP8mVdOjk2KnSAP97dhi
